-- SSM Website: Service Categories Management
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard/project/qkiiismsqqfkonxxwaid/sql/new)

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.service_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    img TEXT,
    icon TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable RLS
ALTER TABLE public.service_categories ENABLE ROW LEVEL SECURITY;

-- 3. Create Policy (Allow all for now, similar to other tables)
DROP POLICY IF EXISTS "Allow all on service_categories" ON public.service_categories;
CREATE POLICY "Allow all on service_categories" ON public.service_categories FOR ALL USING (true) WITH CHECK (true);

-- 4. Seed with current hardcoded data
DELETE FROM public.service_categories;
INSERT INTO public.service_categories (name, img, icon) VALUES
('Steel products', 'https://images.unsplash.com/photo-1590069230005-db393739d22b?q=80&w=800&auto=format&fit=crop', 'Fence'),
('UPVC products', 'https://images.unsplash.com/photo-1503708928676-1cb796a0891e?q=80&w=800&auto=format&fit=crop', 'LayoutPanelLeft'),
('Interiors', 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?q=80&w=800&auto=format&fit=crop', 'DoorOpen'),
('Iron Works', 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop', 'Hammer'),
('Home lifts', 'https://images.unsplash.com/photo-1588613146197-2fed2e05df5e?q=80&w=800&auto=format&fit=crop', 'Construction');
